/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */
 
export const projectId = "uygmnmndqocnzjyjevla"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5Z21ubW5kcW9jbnpqeWpldmxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA3MzY0MDQsImV4cCI6MjA5NjMxMjQwNH0.37hyvU9P1hfO6vaQMltUsud7zyoOBVoSLWQtuhA31IU"
